apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  labels:
    type: local
    env: prod
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data_k8s/lib-odoo"
